name: refresh-data
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '48 22 6/7,30 * *' # runs every 6/13/20/27/30 of each month at 22:48

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Initialize python env
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests tqdm beautifulsoup4 lxml
      - name: Clone steam_stats
        run: |
          git clone https://github.com/dbeley/steam_stats
      - name: Extract Steam appids of owned games
        run: |
          python steam_stats/scripts/get_ids.py -u $STEAM_USER_ID -f ids.csv -t owned
        env:
          STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
          STEAM_USER_ID: ${{ secrets.STEAM_USER_ID }}
      - name: Extract playtime data
        run: |
          python steam_stats/scripts/get_playtime.py -u $STEAM_USER_ID -f playtime.csv
        env:
          STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
          STEAM_USER_ID: ${{ secrets.STEAM_USER_ID }}
      - name: Extract Steam data from appids
        run: |
          python -m steam_stats.steam_stats -f ids.csv --export_filename game_info.csv
        env:
          STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
          STEAM_USER_ID: ${{ secrets.STEAM_USER_ID }}
      - name: Cleanup repository
        run: |
          rm -r steam_stats
      - name: Create new export
        run: |
          python steam_html_builder.py
      - name: Pull remote changes
        run: |
          git pull
      - uses: stefanzweifel/git-auto-commit-action@v4
